import type { Micronutrient } from "./types";

export function getMicronutrients(
  age: number,
  gender: "male" | "female"
): Micronutrient[] {
  const isMale = gender === "male";
  const isAdult = age >= 19;
  const isSenior = age >= 51;

  return [
    // Vitamins
    {
      name: "Vitamin A",
      unit: "mcg RAE",
      rda: isMale ? 900 : 700,
      upperLimit: 3000,
      sources: ["Gan", "Cà rốt", "Khoai lang", "Rau xanh đậm"],
      icon: "🥕",
      category: "vitamin",
    },
    {
      name: "Vitamin B1 (Thiamine)",
      unit: "mg",
      rda: isMale ? 1.2 : 1.1,
      sources: ["Thịt lợn", "Ngũ cốc nguyên hạt", "Đậu Hà Lan", "Hạt hướng dương"],
      icon: "🌾",
      category: "vitamin",
    },
    {
      name: "Vitamin B2 (Riboflavin)",
      unit: "mg",
      rda: isMale ? 1.3 : 1.1,
      sources: ["Sữa", "Trứng", "Thịt nạc", "Rau lá xanh"],
      icon: "🥛",
      category: "vitamin",
    },
    {
      name: "Vitamin B3 (Niacin)",
      unit: "mg NE",
      rda: isMale ? 16 : 14,
      upperLimit: 35,
      sources: ["Thịt gà", "Cá ngừ", "Lạc", "Ngũ cốc"],
      icon: "🐟",
      category: "vitamin",
    },
    {
      name: "Vitamin B6",
      unit: "mg",
      rda: isSenior ? (isMale ? 1.7 : 1.5) : 1.3,
      upperLimit: 100,
      sources: ["Cá hồi", "Khoai tây", "Chuối", "Ức gà"],
      icon: "🍌",
      category: "vitamin",
    },
    {
      name: "Vitamin B9 (Folate)",
      unit: "mcg DFE",
      rda: 400,
      upperLimit: 1000,
      sources: ["Rau lá xanh", "Đậu lăng", "Măng tây", "Cam"],
      icon: "🥬",
      category: "vitamin",
    },
    {
      name: "Vitamin B12",
      unit: "mcg",
      rda: 2.4,
      sources: ["Thịt đỏ", "Cá", "Sữa", "Trứng"],
      icon: "🥩",
      category: "vitamin",
    },
    {
      name: "Vitamin C",
      unit: "mg",
      rda: isMale ? 90 : 75,
      upperLimit: 2000,
      sources: ["Ổi", "Ớt chuông", "Cam", "Dâu tây", "Bông cải xanh"],
      icon: "🍊",
      category: "vitamin",
    },
    {
      name: "Vitamin D",
      unit: "IU",
      rda: isSenior ? 800 : 600,
      upperLimit: 4000,
      sources: ["Ánh nắng mặt trời", "Cá béo", "Nấm", "Sữa tăng cường"],
      icon: "☀️",
      category: "vitamin",
    },
    {
      name: "Vitamin E",
      unit: "mg",
      rda: 15,
      upperLimit: 1000,
      sources: ["Dầu thực vật", "Hạt hướng dương", "Hạnh nhân", "Rau lá xanh"],
      icon: "🌻",
      category: "vitamin",
    },
    {
      name: "Vitamin K",
      unit: "mcg",
      rda: isMale ? 120 : 90,
      sources: ["Rau muống", "Bông cải xanh", "Rau chân vịt", "Đậu nành"],
      icon: "🥦",
      category: "vitamin",
    },
    // Minerals
    {
      name: "Canxi",
      unit: "mg",
      rda: isSenior ? 1200 : isAdult ? 1000 : 1300,
      upperLimit: 2500,
      sources: ["Sữa", "Phô mai", "Đậu phụ", "Rau lá xanh", "Cá nhỏ"],
      icon: "🦴",
      category: "mineral",
    },
    {
      name: "Sắt",
      unit: "mg",
      rda: isMale ? 8 : age < 51 ? 18 : 8,
      upperLimit: 45,
      sources: ["Thịt đỏ", "Gan", "Đậu lăng", "Rau bina", "Hàu"],
      icon: "🩸",
      category: "mineral",
    },
    {
      name: "Magiê",
      unit: "mg",
      rda: isMale ? (isSenior ? 420 : isAdult ? 400 : 400) : isSenior ? 320 : 310,
      upperLimit: 350,
      sources: ["Hạt bí ngô", "Rau lá xanh", "Đậu đen", "Chocolate đen"],
      icon: "🌰",
      category: "mineral",
    },
    {
      name: "Kẽm",
      unit: "mg",
      rda: isMale ? 11 : 8,
      upperLimit: 40,
      sources: ["Hàu", "Thịt bò", "Cua", "Đậu nành", "Hạt điều"],
      icon: "🦪",
      category: "mineral",
    },
    {
      name: "Kali",
      unit: "mg",
      rda: isMale ? 3400 : 2600,
      sources: ["Chuối", "Khoai lang", "Rau bina", "Đậu trắng", "Cá hồi"],
      icon: "🍌",
      category: "mineral",
    },
    {
      name: "Natri",
      unit: "mg",
      rda: 1500,
      upperLimit: 2300,
      sources: ["Muối (hạn chế)", "Nước tương", "Phô mai", "Thịt chế biến"],
      icon: "🧂",
      category: "mineral",
    },
    {
      name: "Phốt-pho",
      unit: "mg",
      rda: 700,
      upperLimit: 4000,
      sources: ["Sữa", "Thịt", "Cá", "Trứng", "Các loại hạt"],
      icon: "🐟",
      category: "mineral",
    },
    {
      name: "Selen",
      unit: "mcg",
      rda: 55,
      upperLimit: 400,
      sources: ["Hạt Brazil", "Cá ngừ", "Thịt lợn", "Trứng"],
      icon: "🥜",
      category: "mineral",
    },
    {
      name: "Iốt",
      unit: "mcg",
      rda: 150,
      upperLimit: 1100,
      sources: ["Muối iốt", "Rong biển", "Hải sản", "Sữa"],
      icon: "🌊",
      category: "mineral",
    },
  ];
}
